// <auto-generated />
using System;
using Gx.DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gx.DataLayer.Migrations
{
    [DbContext(typeof(GxDbContext))]
    [Migration("20220911215426_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gx.DataLayer.Entities.Account.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<long>("CreateUserId");

                    b.Property<bool>("IsActivated");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<bool>("Status");

                    b.Property<long>("UpdateUserId");

                    b.Property<string>("fldActiveCode")
                        .HasMaxLength(10);

                    b.Property<int>("fldActiveCodeExpireDate");

                    b.Property<int>("fldActiveCodeExpireTime");

                    b.Property<long>("fldMobile");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Gx.DataLayer.Entities.ShopDetail.ShopDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<long>("CreateUserId");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<long>("ShopListId");

                    b.Property<bool>("Status");

                    b.Property<long>("UpdateUserId");

                    b.Property<short>("fldCount");

                    b.Property<string>("fldCurrency");

                    b.Property<string>("fldCurrenySymbol");

                    b.Property<string>("fldDescription")
                        .HasMaxLength(500);

                    b.Property<bool>("fldGetData");

                    b.Property<double>("fldMinPrice");

                    b.Property<double>("fldRealPrice");

                    b.Property<string>("fldUrl")
                        .IsRequired()
                        .HasMaxLength(1500);

                    b.HasKey("Id");

                    b.HasIndex("ShopListId");

                    b.ToTable("ShopDetail");
                });

            modelBuilder.Entity("Gx.DataLayer.Entities.ShopList.ShopList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<long>("CreateUserId");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<bool>("Status");

                    b.Property<long>("UpdateUserId");

                    b.Property<string>("fldDescription")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<double>("fldTargetPrice");

                    b.Property<short>("fldTargetPriceCurrency");

                    b.Property<string>("fldTitle")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.HasKey("Id");

                    b.ToTable("ShopList");
                });

            modelBuilder.Entity("Gx.DataLayer.Entities.ShopDetail.ShopDetail", b =>
                {
                    b.HasOne("Gx.DataLayer.Entities.ShopList.ShopList", "ShopList")
                        .WithMany("ShopDetail")
                        .HasForeignKey("ShopListId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
